version: 0.2

phases:
 install:
  commands:
    - echo "starting codeql installation"
    - wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
    - tar -xvzf ./codeql-bundle-linux64.tar.gz
    - export PATH=$PATH:/$CODEBUILD_SRC_DIR/codeql
    - mvn --version
    - java --version
    - echo "creating data base"
    - codeql database create --language=java $CODEBUILD_SRC_DIR/java-database --overwrite --command='mvn clean install'
    - touch example.sarif
    - codeql database analyze $CODEBUILD_SRC_DIR/java-database --format=sarif-latest --sarif-category=java --output=example.sarif
    - echo "$github_token" | codeql github upload-results --repository=keerthana2022/simple-java-project --ref=refs/heads/master --sarif=example.sarif --github-auth-stdin
    
    
