name: Dependabot Jira

on: workflow_dispatch

env:
  GH_SECURITY_TOKEN: ${{ secrets.GITHUBPT }}
  JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  JIRA_HOST:  https://keerthanatest.atlassian.net
  JIRA_USER: keerthanagvsl64@gmail.com
  JIRA_PROJECT: TES
  JIRA_ISSUE_TYPE: Story

jobs:
  create_jira:
    name: Dependabot Jira
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ env.JIRA_HOST }}
        JIRA_USER_EMAIL: ${{ env.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v2.0.1
      with:
        project: ${{ env.JIRA_PROJECT }}
        issuetype: ${{ env.JIRA_ISSUE_TYPE }}
        summary: |
          [${{github.event.repository.name }}] ${{github.event.pull_request.title }}
        description: |
          ${{github.event.pull_request.html_url }}
